version: 2.1

jobs:
  conda_heyoka_head_39:
    docker:
    - image: cimg/base:current
    resource_class: large
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_conda_heyoka_head_39.sh
    - store_artifacts:
        path: doc/_build/html
  conda_heyoka_head_310:
    docker:
    - image: cimg/base:current
    resource_class: large
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_conda_heyoka_head_310.sh
    - store_artifacts:
        path: doc/_build/html
  conda_heyoka_head_312:
    docker:
    - image: cimg/base:current
    resource_class: large
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_conda_heyoka_head_312.sh
  conda_heyoka_head_release_310:
    docker:
    - image: cimg/base:current
    resource_class: large
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_conda_heyoka_head_release_310.sh
    - store_artifacts:
        path: doc/_build/html
  ubuntu_arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.large
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_ubuntu_arm64.sh
  arm64_manylinux2014-py312:
    docker:
      image: pagmo2/manylinux2014_aarch64_with_deps:latest
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/gha_manylinux.sh

workflows:
  version: 2.1
  all_builds:
    jobs:
    - conda_heyoka_head_39
    - conda_heyoka_head_310
    - conda_heyoka_head_312
    - conda_heyoka_head_release_310
    - ubuntu_arm64
    - arm64_manylinux2014-py312
